version: 2.1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - develop
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
jobs:
  build:
    working_directory: ~/rvw-tester
    docker:
      - image: circleci/node:14.15.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Node Dependencies
          command: npm install
      - run:
          name: Verify Build Compiles
          command: npm run build
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  test:
    working_directory: ~/rvw-tester
    docker:
      - image: circleci/node:14.15.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Run Tests
          command: npm test
